- guide/reporting.html
- guide/running.html
- guide/submitting.html
These guides claim to link to a CSS stylesheet:
```
<link
href="http://www.w3.org/XML/Group/xquery-test/TestSuiteStagingArXQTSCatalogExplain.html"
rel="stylesheet" type="text/css" />
```
1. That file is inaccessible without W3C credentials.
2. I don't believe it's a CSS stylesheet
I removed it.
> Remove bogus references to an HTML file as a CSS stylesheet

- fn/expanded-QName.xml
- fn/parse-xml-fragment.xml
@michaelhkay I believe we can get rid of the keyword argument syntax in these particular test cases.
> Keyword arguments replaced by conventional arguments

- catalog.xml
- fn/items-ending-where.xml
- fn/items-starting-where.xml
Functions renamed (qt4cg/qtspecs#149)
> fn:items-(until|from) → fn:items-(ending|starting)-where. qt4cg/qtspecs#149

- fn/trunk.xml
Just updating the spec dependency to 40.
> The fn:trunk tests require 4.0

- fn/build-uri.xml
- fn/parse-uri.xml
This PR changes the arrays in `parse-uri` output (and `build-uri` input) to sequences.
(This is speculative as I haven't implemented the changes yet.)
> Resolve action QT4CG-042-01, use sequences instead of arrays in parse-uri/build-uri

- fn/build-uri.xml
- fn/parse-uri.xml
1. There are some typos with respect to where `"` appears in the results of a couple of `fn:build-uri` tests. I've also changed the test so that either `"` or `%22` is accepted. I can't find any motivation in RFC 3986 to encode `"`, but it's often done.
2. In the `fn:parse-uri` tests, when we changed from arrays to sequences, the square brackets were accidentally left in test 041.
> Fixes for fn:parse-uri and fn:build-uri

- fn/parse-uri.xml
Discovered this test was missing while cleaning up the spec.
(I haven't attempted to sort out the `&` problems with backticks yet, but it's on my list.)
> Test for parsing repeated query parameters

- catalog.xml
- prod/ForClause.map.xml
Tests for the `for key $k value $v` syntax, as proposed in qt4cg/qtspecs#31.
> FLWOR: for key $k value $v. qt4cg/qtspecs#31

- fn/build-uri.xml
- fn/parse-uri.xml
This PR adds a comprehensive set of tests for encoding and decoding characters in URIs. All of the characters from space (`%20`) to ~ (`%7E`) and a range of higher Unicode characters and emoji are included. This should assure that implementations get consistent results for both parsing URIs (and decoding the parts of the URI) and building URIs (and encoding the parts of the URI).
The test results are (to the best of my knowledge at the moment) correct and consistent with both `fn:decode-for-uri` and the notes in https://github.com/qt4cg/qtspecs/issues/774
(I hope I've encoded the tests so that they work with the XQuery driver; apologies if I messed up anywhere. I'd be very interested in hearing what differences, if any, other implementations give.)
> Comprehensive encoding/decoding tests

- fn/format-time.xml
In date/time formatting, BaseX used to generate mixed case AM/PM and era indicators as `Am`, `Pm`, `Bc`, `Ad`. This is about to be changed to `AM`, `PM`, `BC`, `AD` (see BaseXdb/basex#2273), which consequently requires alternate results for test cases `format-time-021` and `format-time-022`.
> Add alternate results to format-time-021 and format-time-022

- catalog-schema.scm
I'm not especially sanguine about committing vendor-specific artifacts, but this will allow the CI runner to operate without having to have a Saxon license. That seems like a fair trade-off, but if you object, let me know.
> Added a Saxon compiled schema for catalog

- fn/format-integer.xml
As pointed out in qt4cg/qt4tests#66, there may be more than one fallback strategy for ICU rule set names that cannot be matched exactly, and BaseX has chosen to implement one that does not match the expectation of test case [format-integer-077](https://github.com/qt4cg/qt4tests/blob/3392bd4e821b8434b2ff238004ddf6eb04ace891/fn/format-integer.xml#L748-L760).
This changes adds an alternate result, corresponding to BaseX behavior.
> Add alternate result to format-integer-077 (fixes qt4cg/qt4tests#66)

- fn/lower-case.xml
- fn/upper-case.xml
Test `fn-upper-case-19` expects `fn:upper-case` to map `&#1011;` (`&#x3F3`) to itself. The test is marked with
```xml
<dependency type="unicode-version" value="7.0"/>
```
however Unicode version 7.0 has added `&#895;` (`&#x37F`) as the upper-case mapping (see [here](https://www.unicode.org/Public/7.0.0/ucd/UnicodeData.txt)).
Saxon 12.4 still maps to `&#1011;`, even though Java 11 maps to `&#895;` - does Saxon possibly maintain an out-of-date mapping?
> Fix upper-case mapping of '&#1011;'

- fn/replace.xml
In some of the tests for `fn:replace`, that were added recently by be8f43b, the replacement string has a different order of components than the expected result.
> Correct newly added fn:replace tests

- misc/HigherOrderFunctions.xml
Test case `hof-919` asks for a `XPTY0004` error, because a function expecting an `xs:float` argument did not accept `xs:double`. This was not permitted when the test case was created, but it is valid per the [new coercion rules](https://qt4cg.org/specifications/xquery-40/xquery-40-diff.html#id-coercion-rules).
Apparently the test case was created from `hof-044`, which was then modified to the function expecting `xs:double`. I propose to revert that change and mark test case `hof-044` with a dependency of `XQ40+`.
> Adapt test case hof-919 to new coercion rules

- fn/build-uri.xml
I'm still working my way through https://github.com/qt4cg/qtspecs/issues/566 ...
This PR is attempting to fix the same errors that I described in #94 but uses the backtick string interpolation feature to make a string that (I believe) works the same in both XQuery and XPath.
> Another attempt to fix escaping issues in the test

- fn/parse-uri.xml
Based on the results that @ChristianGruen provided and upon closer inspection of the specification, I think these results are correct.
I think it's an open question whether they are the results we want, but they are correct with respect to what the specification currently says.
> Fix expeced results of fn-parse-uri-011c

- fn/while-do.xml
> 103 while-do-error-004: Reference wrongly typed variable

- prod/EnumerationType.xml
The test cases in `prod/EnumerationType.xml` expect that
- an `xs:string` literal is acceptable as an `instance of` an `enum` type,
- an `enum` type is not accepted on the right hand side of a `cast as` operator.
Either of this is not in line with the current specification. This change modifies the tests accordingly, adding additional `castable as` test cases to the `instance of` ones.
> Adapt enum test cases to current state of the specification

- ser/method-adaptive.xml
The spec PR changes the adaptive output from `map{}` to `{}`.
> PR1123 Adaptive output changes for 4.0

- array/filter.xml
- array/index-where.xml
- fn/codepoints-to-string.xml
- fn/contains-subsequence.xml
- fn/deep-equal.xml
- fn/do-until.xml
- fn/ends-with-subsequence.xml
- fn/every.xml
- fn/filter.xml
- fn/index-where.xml
- fn/load-xquery-module.xml
- fn/partition.xml
- fn/some.xml
- fn/starts-with-subsequence.xml
- fn/subsequence-where.xml
- fn/take-while.xml
- fn/while-do.xml
- map/filter.xml
- map/keys-where.xml
- prod/ChoiceItemType.xml
- prod/FunctionDecl.xml
- prod/Lookup.xml
- prod/WindowClause.xml
Add tests for functions with a boolean callback that can now return an empty sequence
> PR1182 predicates returning empty sequence

- prod/DynamicFunctionCall.xml
If my reading of the spec, as explained in #135, is correct, test case `DynamicFunctionCall-136` should expect `XPTY0004`.
> Expect coercion of xs:anyURI to enum to be rejected in test case DynamicFunctionCall-136

- prod/DynamicFunctionCall.xml
The test cases with prefix `DynamicFunctionCall-R-` were apparently derived from the corresponding test cases with prefix `DynamicFunctionCall-` (without `R-`).
This change fixes these problems:
- `DynamicFunctionCall-R-081` has a typo in the `record` keyword. Also, like its counterpart `DynamicFunctionCall-081`, it may expect `FORG0001`
- `DynamicFunctionCall-R-136` expects coercion from `xs:anyURI` to `enum`, which does not happen per the spec. The same issue for `DynamicFunctionCall-136` was discussed in #135 and fixed in #136.
> Fixes of RecordTest test cases in DynamicFunctionCall.xml

- fn/parse-uri.xml
These are updated test results and a few new tests for `fn:parse-uri`. I'd be curious to know if someone else thinks:
1. They are "correct", are these the results we want?
2. Are they consistent with the specification in https://github.com/qt4cg/qtspecs/pull/1244
> qtspecs1244 Updated tests for fn:parse-uri

- misc/HigherOrderFunctions.xml
The signature of `fn:filter` has changed in [4.0](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-filter) to allow a predicate returning `xs:boolean?`, rather than `xs:boolean` in [3.1](https://www.w3.org/TR/xpath-functions-31/#func-filter), making test case `xqhof21` return a result in 4.0, rather than fail with `XPTY0004` in 3.1. 
This change thus adds `xqhof21a` to cover 4.0+ behaviour.
> Adapt test case xqhof21 to changed signature of fn:filter

- prod/FunctionCall.xml
Test case `FunctionCall-422` currently asks for a result of `1` from this query:
```xquery
function-arity(contains(?, 23))
```
However it should return a type error: `function-arity` has to return the arity of the function identified by the given function item, which in this case is constructed according to the rules provided in [4.5.2.3 Partial Function Application](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-partial-function-application). For static function calls they say:
> A type error is raised if any of the explicitly supplied or defaulted parameters, after applying the coercion rules, does not match the required type of the corresponding parameter.
This applies here - the explicitly supplied parameter has a type of `xs:integer`, but the type of the second …
> Change expected result of FunctionCall-422

- misc/HigherOrderFunctions.xml
- prod/FunctionCall.xml
- prod/NamedFunctionRef.xml
Following up on the discussion in qt4cg/qt4tests#148, these changes take care of allowing both a result and a type error from invocations of `fn:function-arity` in cases where the given function item
- refers to a non-executed function with errors in the function body
- is a partially applied function where some explicitly supplied parameter is not suitable.
This affects test cases
- `xqhof40`
- `xqhof41`
- `xqhof43`
- `xqhof44`
- `FunctionCall-422`
- `named-function-ref-function-arity-902`
Test case `named-function-ref-function-arity-902` is now identical to test case `named-function-ref-function-arity-901`, apart from its annotations. Should it rather be removed?
> Allow result from fn:function-arity where arity can be calculated despite some error

- prod/ItemTypeDecl.xml
In [3.2 Item Types](https://qt4cg.org/specifications/xquery-40/xquery-40.html#id-matching-item), the spec explains how to interpret an EQName occurring as an item type designator, and eventually it says:
> If the name cannot be resolved to a type, a [static error](https://qt4cg.org/specifications/xquery-40/xquery-40.html#dt-static-error) is raised [[err:XPST0051](https://qt4cg.org/specifications/xquery-40/xquery-40.html#ERRXPST0051)].
In contrast to this, `itemTypeDecl-007` and `itemTypeDecl-010` currently ask for a general parsing error [[err:XPST0003](https://qt4cg.org/specifications/xquery-40/xquery-40.html#ERRXPST0003)].
This change modifies the expected error code accordingly.
> Expect XPST0051 for undefined type in test cases 

- fn/parse-uri.xml
Fixes issues described in https://github.com/qt4cg/qtspecs/issues/1381 and adds a new tests for the proposed change to handling the query string (addressed in https://github.com/qt4cg/qtspecs/pull/1380)
> Improvements to tests for fn:parse-uri

- fn/build-uri.xml
- fn/parse-uri.xml
I've attempted to update our implementation to reflect the latest status quo draft and modified the tests accordingly.
Encoding the `+` in the `tel:` scheme is [discussed in the issue](https://github.com/qt4cg/qtspecs/issues/1387#issuecomment-2345645361).
> Updated parse and build uri results

- prod/DecimalFormatDecl.xml
Per qt4cg/qtspecs#1048, implemented by qt4cg/qtspecs#1250, and [test case `numberformat-550`](https://github.com/GuntherRademacher/qt4tests/blob/17d7b573ff9d2b5d056e4b3fbc9c8dd83466a693/fn/format-number.xml#L3772), a decimal format `minus-sign` may now be an arbitrary string, rather than a single character.
This change adapts test case `decimal-format-911err` accordingly by making it dependent on `XQ30` `XQ31` and spawing `decimal-format-911err-a` for `XQ40+`, expecting a different error code.
> Adapt test case `decimal-format-911err-a` to recent changes

- fn/sort-with.xml
- prod/CompElemConstructor.xml
This change fixes two test cases:
- `sort-with-018`: this was using the braced-if syntax, and it is changed to unbraced
- `K2-ComputeConElem-20`: this asked for a parsing error `XPST0003` for the statement `element div {}`, based on the idea that `div` is not allowed as an unqualified element name. However this parses successfully as a `div` operator with a name on the left hand side and a map constructor on the right hand side. This may not be a valid division expression, but the grammar allows it to be parsed this way, so the test should not expect a parsing error. The expectation is replaced by the error codes that Saxon and BaseX come up with for expressions that try to divide by an empty map.
> Change tests asking for parser success/failure where it should be failure/success 

- fn/atomic-type-annotation.xml
- fn/node-type-annotation.xml
Some tests for `fn:atomic-type-annotation` and `fn:node-type-annotation` require typed data, but are not marked with a `typedData` dependency. 
This change adds the missing dependencies.
> Add missing `typedData` dependencies to some tests for `fn:atomic-type-annotation` and `fn:node-type-annotation`

- fn/highest.xml
- fn/load-xquery-module.xml
- fn/serialize.xml
- misc/Subtyping.xml
- prod/ArrayTest.xml
- prod/ArrowExpr.xml
- prod/DynamicFunctionCall.xml
- prod/FunctionCall.xml
- prod/MapTest.xml
- prod/StringTemplate.xml
Many tests have dependencies in the form 
```
<dependency type="spec" value="XP40+ XQ40+"/>
```
However, some of them only parse correctly with XQuery 4.0, not with XPath 4.0.
This change removes the `XP40+` annotations for these cases.
> Remove ‘XP40+’ dependency from tests that do not conform to XPath 4.0 grammar

- fn/parse-xml-fragment.xml
- fn/parse-xml.xml
- prod/ForClause.xml
- prod/WhileClause.xml
Apparently the comparison of test results must be performed under conditions where boundary space is stripped. If it were preserved, 8 tests would fail, e.g.
- [`ForExprType009`](https://github.com/qt4cg/qt4tests/blob/87590dd60a281151c1dab4ef3f98d1e4a6eb1ac7/prod/ForClause.xml#L1725-L1739)
- [`WhileExpr0006`](https://github.com/qt4cg/qt4tests/blob/87590dd60a281151c1dab4ef3f98d1e4a6eb1ac7/prod/WhileClause.xml#L105-L135)
- [`WhileExpr007`](https://github.com/qt4cg/qt4tests/blob/87590dd60a281151c1dab4ef3f98d1e4a6eb1ac7/prod/WhileClause.xml#L137-L152)
However with boundary space stripped, the currently expected test results for option `strip-space` of `parse-xml` and `parse-xml-fragment` would compare OK regardless of whether the option is implemented or not.
This change thus moves text node …
> Make tests for `parse-xml` option `strip-space` independent of boundary space

- fn/analyze-string.xml
There are four matches that can be reported by `analyze-string("abc", "a|b|c?")`, and the spec does not say that the final empty match should be suppressed, so this change is adding it to the expected result.
> Add missing empty fn:match to the expected result of `analyzeString-903a`

- fn/doc-available.xml
- fn/doc.xml
- fn/parse-xml.xml
These fixes came up while working on the new options:
**`fn/doc-available.xml`**
- added missing environment `works-mod-uri`
- `fn-doc-available-1`: `fn:doc-available` now allows two parameters. so added a dependency on versions before 4.0
- `fn-doc-available-1a`: spawned from `fn-doc-available-1` to reflect 4.0 behaviour
- `fn-doc-available-40-017`: removed excess left parenthesis
- `fn-doc-available-40-021`: corrected expected response (test does not exceed entity expansion limit)
**`fn/doc.xml`**
- `fn-doc-2`: `fn:doc-available` now allows two parameters. so added a dependency on versions before 4.0
- `fn-doc-2a`: spawned from `fn-doc-2` to reflect 4.0 behaviour
- `fn-doc-40-011`: XML parser reports a DTD validation error, so added response code `FODC0007`
- `fn-doc-40-012`: XML parser …
> Test cases relating to new options of `fn:doc`, `fn:doc-available`, and `fn:parse-xml`

- fn/element-to-map-plan.xml
- fn/xsd-validator.xml
Test `xsd-validator-074` had a syntax error, a semicolon was missing.
A number of new tests had dependency `XP40+ XQ40+`, though they are not valid for XPath.
This was detected by the test processing for the [RExified](https://github.com/GuntherRademacher/rex-parser-generator/tree/main/docs/sample-grammars/XQuery-40) grammars.
As noted [here](https://github.com/GuntherRademacher/rex-parser-generator/blob/51b5302a5d1471592b3d24d60157131b2c5beadf/docs/sample-grammars/XQuery-40/process-tests.xq#L14-L30), there are also a few more problems with tests in [app/fo-spec-examples.xml](https://github.com/qt4cg/qt4tests/blob/master/app/fo-spec-examples.xml) , but those tests are generated ones.
> Corrections of new tests

- prod/CompAttrConstructor.xml
- prod/CompElemConstructor.xml
- prod/ExtensionExpr.xml
- prod/Literal.xml
- prod/ValidateExpr.xml
A number of tests have been adapted to the new syntax for computed constructors, QName literals, and pragmas. Two tests were removed completely, because they were testing discontinued aspects.
> Adapt tests to new syntax of pragmas, QName literals, and computed constructors

- array/sort-by.xml
- fn/sort-by.xml
- prod/Literal.xml
A few problems were found by [REx test processing](https://github.com/GuntherRademacher/rex-parser-generator/tree/main/docs/sample-grammars/XQuery-40):
- `fn-sort-by-spec-4` missing `XQ40+` dependency
- `fn-sort-by-spec-5` missing `XQ40+` dependency
- `array-sort-by-022` missing `XQ40+` dependency
- `Literals-40-925a` extraneous expected result since recent merge
> Fix problems detected by parser tests

- fn/random-number-generator.xml
- prod/SequenceType.xml
While working on built-in record types, I found that these tests need to be fixed:
-  `built-in-record-type-003`
This supplies a `get` function returning `xs:string?`, but this does not match with `fn:parsed-csv-structure-record` which asks for `get` to return `xs:string`
- `fn-random-number-generator-35` through `fn-random-number-generator-37`
These check a function item returning `fn:random-number-generator-record` using
```xml
<assert-type>function() as map(xs:string, item())</assert-type>
```
However `fn:random-number-generator-record` is extensible, so it should be either or both of
```xml
<assert-type>function() as map(xs:anyAtomicType, item()*)</assert-type>
<assert-type>function() as fn:random-number-generator-record</assert-type>
```
> Test fixes related to built-in record types

- fn/parse-csv.xml
`fn:parse-csv` was recently ([f2e1f48](/qt4cg/qtspecs/commit/f2e1f48416a89bd1e8189ebebc060b406197f9da)) changed to return an empty sequence, but `parse-csv-001` still expects it to return an empty map.
Also, I am adding an alternative error code to `parse-csv-907`, on the grounds that `FOCV0002` (Invalid CSV delimiter error) can be considered an acceptable response for
```xquery
fn:parse-csv('one,two', map{'row-delimiter':('|','||')})
```
> Adapt `fn:parse-csv` tests

- prod/Literal.xml
- prod/Lookup.xml
- prod/UnaryLookup.xml
`KeySpecifier` has recently ([e26b54c](https://github.com/qt4cg/qtspecs/commit/e26b54c337ea4b1eea7d194a4555ca5218729589)) been extended to allow any literal, and context value references. This change adapts a number of tests accordingly.
> Adapt tests to changed syntax of `KeySpecifier`
